[build]
  command = "npm run build"
  publish = "public"
  environment = {NODE_VERSION = "18.20.4"}

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' https://player.vimeo.com; script-src 'self' 'unsafe-inline' https://www.google-analytics.com https://www.googletagmanager.com; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:; object-src 'none'; frame-ancestors 'none'; connect-src 'self' https://www.google-analytics.com"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains;"
    X-Content-Type-Options = "nosniff"
